### ISSUE TITLE
Failed: Could not find executable to launch.

### ISSUE THREAD

**Issue by grishatop1** [dmadisetti/steam-tui#42]
Whichever game I try launching, it gives me the error in the title, along with "Try setting $STEAM_APP_DIR". I have set it to path /home/grisha/.local/share/Steam. What do I need to do to make this work?
steam-tui | 0.2.1-4 from AUR

**Comment by dmadisetti** [comment]
This might happen for Games requiring proton or Windows games. Try pressing space once `steam-tui` loads to boot up steam in the background.

Alternatively try `steam-run steam-tui`

Let me know if this works?

As for solutions from steam-tui, I'd like suggestions- but I think steam-tui should leave an editable bash script that can be tweaked on a per system / game basis.

**Comment by dmadisetti** [comment]
Neither of em launch? Native should absolutely launch. Could be a library issue? If you have steam-run try `steam-run steam-tui` and that should be fine. Also, depending on your install it might be `/home/grisha/.local/share/steam` not `/home/grisha/.local/share/Steam`

can you do `steam-tui 2> wtf.log` otherwise?

Thanks for the star all the same :star: :tada:

**Comment by grishatop1** [comment]
Hey!! Sorry for long responses..
I did `steam-tui 2> wtf.log` and it wrote this
```
script_path - "/home/grisha/.local/share/Steam/steamapps/Counter-Strike Global Offensive/csgo.sh"

script_path - "/home/grisha/.local/share/Steam/steamapps/Counter-Strike Global Offensive/csgo.exe"

script_path - "/home/grisha/.local/share/Steam/steamapps/Counter-Strike Global Offensive/csgo.sh"
```
Then I've checked those paths and they seem to be wrong, because the real path of csgo.sh is
`/home/grisha/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/`
(difference is this "common" folder)
