### ISSUE TITLE
Some parts of `steam-tui` are barely readable on light terminals

### ISSUE THREAD

**Issue by Zeerooth** [dmadisetti/steam-tui#46]
![1661714749](https://user-images.githubusercontent.com/27929520/187091624-da2d2a1f-2f3d-42f2-a98e-9e850225d314.png)

^ as shown above

It's especially hard to read on lower brightness settings. I think the main reason for that are the hardcoded colours, for example [here](https://github.com/dmadisetti/steam-tui/blob/1ce4e68f38666ecd4e5dd9ebc63c0d83cb1d7f86/src/app.rs#L147). I think removing them might partially fix the issue as terminals should determine default colour themselves or use a crate like https://github.com/Canop/terminal-light to detect the style.

**Comment by dmadisetti** [comment]
For sure, there is already configuration for the highlighting: https://github.com/dmadisetti/steam-tui/blob/b56fef8498a7cf372c83c12ef9bd6cdb482f398f/src/app.rs#L75

It would just be a matter of adding more color fields to Config: https://github.com/dmadisetti/steam-tui/blob/b56fef8498a7cf372c83c12ef9bd6cdb482f398f/src/config.rs#L17

Another point would be extending `tui-image` for background burn modes (currently alpha is assumed against a black background): https://github.com/AnotherGroupChat/tui-image/blob/bd44e59e0ffc0b7f5344bd02f4b22ec820025e30/src/lib.rs#L39

`terminal-light` is a nice find- but it's simple enough I'd maybe want to port it rather than include it as a dep? Maybe it's worth just adding another dep, but really we'd just use it to backfill for a default colour scheme

**Comment by dmadisetti** [comment]
Ohhh yeahh, all those `App` functions are static because clippy yelled at me when I was too lazy to add all the color options, bit of churn to make them not static, but nothing too bad.
